server.port=8080

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:spendsmart_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 web console — accessible at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
application.security.jwt.secret-key=6D5A7134743777217A25432A46294A404E635266556A586E3272357538782F41
application.security.jwt.expiration=86400000

# ML Flask API
ml.api.url=http://localhost:5000/predict

logging.level.org.springframework.security=INFO
